name: Release

on:
  workflow_dispatch:
    inputs:
      build-version:
        required: true
        description: "Release version and its future tag (ex. 1.0.0)"

jobs:
  pypi:
    name: Publish Python package on PyPI
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Flit
        run: python -m pip install flit

      - name: Build package
        run: python -m flit build
        env:
          BUILD_VERSION: ${{ github.event.inputs.build-version }}

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  ghcr:
    name: Publish Docker image on GHCR
    needs: pypi # Dockerfile installs ERDB from PyPI
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: erdb:${{ github.event.inputs.build-version }}
          build_args: BUILD_VERSION=${{ github.event.inputs.build-version }}